name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        default: "prd"
        type: choice
        options:
          - dev
          - uat
          - preprd
          - prd
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # Use the input environment name
    environment: ${{ github.event.inputs.environment || 'prd' }}

    env:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DD_BETA_COMMANDS_ENABLED: 1
      DD_SITE: datadoghq.com # or datadoghq.eu
      DD_GITHUB_JOB_NAME: Deploy to Production
      SERVICE_NAME: "test-tim-service" # Replace with your service name
      REPOSITORY_URL: "https://github.com/timltj/test-actions" # Replace with your repository URL
      COMMIT_SHA: ${{ github.sha }}
      DEPLOY_ENV: ${{ github.event.inputs.environment || 'prd' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and prepare datadog-ci CLI
        run: |
          curl -L --fail "https://github.com/DataDog/datadog-ci/releases/latest/download/datadog-ci_linux-x64" --output "/usr/local/bin/datadog-ci" && chmod +x /usr/local/bin/datadog-ci

      - name: Mark deployment in Datadog
        run: |
          datadog-ci deployment mark --env $DEPLOY_ENV --revision 1.0.0 --tags team:backend --tags reason:scheduled

      - name: Submit DORA Metrics to Datadog
        run: |
          start_time=$(date -u -d '-10 seconds' +'%Y-%m-%dT%H:%M:%SZ') # Simulating a deploy start time 10 seconds ago
          datadog-ci dora deployment \
            --service $SERVICE_NAME \
            --started-at "$start_time" \
            --git-repository-url $REPOSITORY_URL \
            --git-commit-sha $COMMIT_SHA \
            --env $DEPLOY_ENV
